name: Update Spotify Now Playing

on:
  schedule:
    - cron: '*/30 * * * *'  # Her 30 dakikada bir çalışır
  workflow_dispatch:        # Elle de tetikleyebilirsin

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update Spotify Readme
      uses: anuraghazra/github-readme-spotify-action@v1.1.0
      with:
        spotify_client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
        spotify_client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        spotify_refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
